### ISSUE TITLE
Dangling dots, mid-string, are seen as domains

### ISSUE THREAD

**Issue by requaos** [mvdan/xurls#43]
Here I have two small edge-cases:
- `<some.guy@domain.com>` yields `[]string{"some.gu", "domain.com"}`
- `[cid:programmer-thumb-shield-32x32.v2_fe0f1423-2d7d-484b-b624-6b7545ab4311.png]` yields `[]sting{"fe0f1423-2d7d-484b-b624-6b7545ab4311.pn"}`

I'm just wondering about the dropped character before the symbol. This is email, so I can cross-reference against the filenames of inline attachments and also double-check against a known list of TLDs, but dropping that last character makes this difficult.

Any ideas on why that last char is being dropped?

**Comment by mvdan** [comment]
Can you clarify if you're using the strict or relaxed regexp?

**Comment by requaos** [comment]
@mvdan Yes, I am using the `Relaxed` set

**Comment by mvdan** [comment]
In the first case, I assume that you're fine with the `domain.com` match. The `some.gu` match happens beause `gu` is a well-known top-level domain (https://en.wikipedia.org/wiki/.gu). You could argue that we shouldn't match it because the supposed TLD there is `.guy` and not `.gu`, but that's tricky; see 15684420e2b89d5320d909e8f05655c101ab18bc. I could try to fix this, but I think your best attempt is to have a first pass that excludes or parses email addresses, because email usernames could very well resemble valid domains.

As for the second, it sounds like we simply didn't include `cid` into the short list of schemes that don't require `://`, such as `mailto` and `magnet`. I'll fix this.

**Comment by mvdan** [comment]
The second is now fixed in the commit above.

**Comment by requaos** [comment]
Hey @mvdan, happy holidays. Thank you for looking into this. I appreciate your time.
