### ISSUE TITLE
Invalid prefixes for URLs are matched

### ISSUE THREAD

**Issue by HalosGhost** [mvdan/xurls#6]
This is probably due to adding support for arbitrary protocols.

```console
$ echo "systems.https://google.com" | xurls
systems.https://google.com
```

I am unsure of it, but is it actually ever valid for punctuation to exist in the protocol portion of a URL schema?

I know that ``xurls`` wasn't really focusing on being a URL validator. But honestly, we aren't too far from accomplishing that and it would be helpful to know that matches are valid (in terms of the specification).

**Comment by mvdan** [comment]
Okay, good and bad news. The good news is that this isn't a regression, because strictly speaking `system.https` is a valid scheme:

https://tools.ietf.org/html/rfc3986#section-3.1
> Scheme names consist of a sequence of characters beginning with a letter and followed by any combination of letters, digits, plus ("+"), period ("."), or hyphen ("-")

But the bad news is that it does indeed look bad that we match all of that. Not sure how to fix it though, will have to think it through a bit.

Regarding URL validation, we're much much further away from it than you think. For example, we now accept any array of valid characters as the path and options in the URL. If we were to verify the URL, that piece of regex would be much more complex, probably following the RFC.

**Comment by mvdan** [comment]
Either way, I noticed that it says "beginning with a letter", so at least I fixed that bit.

**Comment by mvdan** [comment]
So the real problem here is that you know that `https` is a valid scheme, and prefer that over an arbitrary `foo.bar` scheme, in this case `foo.https`. But if you really had `foo.bar`, we'd pick that over `bar`. The only way to accomplish this is to have a list of well known schemes like `https`.

The only other way is to forbid periods, and even hyphens and plus signs. This would work better in 99% of the cases, but in a 1% of the cases it would incorrectly match schemes like `iris.beep` or `ms-help`.

I'm thinking the latter option is probably best, but I want to think about it twice before dropping support for those kind of schemes in favor of less real-world false positives.

**Comment by HalosGhost** [comment]
I didn't realize those were valid. Since they are, I would recommend against changing anything. Supporting arbitrary schemas (so long as it is being done correctly, as it appears it is) is of a higher priority to me than mangling the parsing to avoid so-called false-positives due to syntactic error in input.

**Comment by mvdan** [comment]
We're doing stuff that looks like urls, not stuff that could be an url. An example of where do these differ is `http://foo.bar/path.`. There is a dot at the end, but we ignore it. We do that because the user most probably wants to extract an url which is at the end of a sentence, thus followed by a period.

The same way that we don't support all valid paths, we could drop support for all valid schemes. We could forbid periods in them, for example, since they are very rare, as plus signs and dashes are. In fact I had never seen urls with schemes like that.

So I'm still thinking it's a good idea to adapt to that.

**Comment by mvdan** [comment]
Moreover, remember that you can still specify your own scheme regex if you want a different behaviour to that of xurls. But I think the default should be "stuff that looks like an url in between text" not "stuff that could be or is a valid url".

**Comment by HalosGhost** [comment]
Well, I can think of at least one case where I might want to match a ``+`` in a URL.

In VCS PKGBUILDs, you specify a vcs tool preceding the URL like so:

```
git+https://some.git.repo/for_a.git#thing
```

Being able to capture all of this would be handy when writing/adapting PKGBUILDs. However, it is your project, adapt it if you want :)

**Comment by mvdan** [comment]
Sure, `+` sounds fine. `.` though...

Most url matching engines/libs/... avoid these issues by hard-coding what schemes they accept. I think our approach is better and more generic, at the cost of these edge cases.

So yeah, for now I won't remove `.` from the scheme regex part.

**Comment by mvdan** [comment]
It just occured to me that you can specify a regex via `-m` that would only include letters if you wanted. So I'm now convinced the current behaviour is correct.

**Comment by HalosGhost** [comment]
I agree, I think ``-m`` takes care of this issue nicely.
