### ISSUE TITLE
authority component parsing does not align with RFC 3987

### ISSUE THREAD

**Issue by gibson042** [mvdan/xurls#62]
Particularly IPv6 addresses, which must be bracketed as in `https://[2001:db8::1]/`.

**Comment by mvdan** [comment]
Since we agreed not to merge https://github.com/mvdan/xurls/pull/63, should we keep this issue open?

**Comment by gibson042** [comment]
I'd be comfortable either way; it would be nice to fix but isn't actively causing issues right now.

**Comment by mvdan** [comment]
Sounds good. I'm going to close for now, then; I think it's most useful to keep issues open if we have identified a practical issue coming up, be it significant false positives or false negatives. Otherwise I'm not too worried about not aligning perfectly with the RFC spec; we already don't by design, because we're working within the constraints of a regular expression that tries to guess where the user intends the URL to end :)
