### ISSUE TITLE
Add file support

### ISSUE THREAD

**Issue by bep** [mvdan/xurls#8]
Useful little util.

It would be nice if it, in addition to the stdin support, could work with file(s) as arguments.

Currently this works:

`cat myfile.txt | xurls`

This just hangs there, waiting:

`xurls myfile.txt`

An example of a Go tool that works as expected for a *nix CLI tool would be `ccat`.

**Comment by mvdan** [comment]
Is it a common pattern for all unix tools that work with stdin/stdout to also accept files as arguments? I don't see why it shouldn't be supported, but just wondering.

I'm also thinking about multiple files. I'm guessing you would have `xurls file1 file2` work just like `cat file1 file2 | xurls`, as in without distinguishing files?

**Comment by mvdan** [comment]
Also, of course the tool hanging when given an argument is a bug :)

**Comment by bep** [comment]
Most of the *nix tools in the GNU Utils package that works on text works on files + stdin, cat, grep, more, less, tail ... So it's common. So common it was the first my fingers tried.

Ideally it should work like `cat` does, so `xurls file1 file2` `xurls *.txt` etc should work.

**Comment by mvdan** [comment]
Done. I've followed the pattern that `cat` uses, explained in the commit for future reference.

**Comment by mvdan** [comment]
I just noticed your mentioning of goroutines. For multiple files it could be used. They are cheap so that shouldn't be a problem, and it could indeed speed things up for large files or async I/O.

The only disadvantage I can think of is that the urls will no longer be output in the correct order like `cat` prints the lines in order, even though at no point we say we're doing them in order.

**Comment by bep** [comment]
The go routines would be a nice addon (not important), but is a different issue.

**Comment by mvdan** [comment]
Could you please open a separate issue describing it?
